### ISSUE TITLE
Release: Add dnadesign to vendor array in .cow.json

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/recipe-kitchen-sink#24]
During the 4.12.0-beta1 release, there was an issue where `dnadesign/silverstripe-elemental-userforms` wasn't being added to the cowpat, and when added manually cow had a cow about it. Adding `dnadesign` to the local version of the `.cow.json` file resolved this and seems like a reasonable long-term resolution.

## Acceptance criteria
- [ ]  `dnadesign/silverstripe-elemental-userforms` gets automatically added to the cowpat when creating a cow release plan

## PRs
- https://github.com/silverstripe/recipe-kitchen-sink/pull/28

**Comment by emteknetnz** [comment]
@GuySartorelli Is this actually an issue? I'm not sure if `dnadesign/silverstripe-elemental-userforms` is even supposed to be released during the cow release? It's not part of the sink?

https://www.silverstripe.org/software/addons/silverstripe-commercially-supported-module-list/ has it down as a "supported dependency" rather than a "supported module"

**Comment by GuySartorelli** [comment]
Huh. I hadn't noticed that. What's the difference between supported dependency and supported module?

**Comment by emteknetnz** [comment]
I'm not sure what the issue is, looking at previous release plans such as 4.11.0 dnadesign/silverstripe-elemental-userforms is being added to the .cow.pat.json.  It is upgrade-only, though it's there.

> Adding dnadesign to the local version of the .cow.json

Which .cow.json?

**Comment by GuySartorelli** [comment]
> Which .cow.json?

recipe kitchen sink's one (aka the release's one) iirc

**Comment by emteknetnz** [comment]
OK, noticed that in my testing that I'm replicating this issue, must have been a regression from some changes since 4.11.0 in cow

I'll add it to .cow.json

**Comment by GuySartorelli** [comment]
PR merged
