### ISSUE TITLE
Broken builds

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/recipe-kitchen-sink#44]
The following builds are broken for 4.13:
- kitchen sink [![CI](https://github.com/silverstripe/recipe-kitchen-sink/actions/workflows/ci.yml/badge.svg?branch=4.13)](https://github.com/silverstripe/recipe-kitchen-sink/actions/workflows/ci.ymlquery=branch%3A4.13)
  - [Recipe content block](https://github.com/silverstripe/recipe-kitchen-sink/actions/runs/5446469407/jobs/9907261786) as some failing scenarios 
  - [MFA in failing](https://github.com/silverstripe/recipe-kitchen-sink/actions/runs/5446469407/jobs/9907262783) because of some MySQL query timing out.

The builds have been failing for a couple days, so it's not intermittent 

### PRs
- https://github.com/silverstripe/silverstripe-elemental/pull/1073
- https://github.com/symbiote/silverstripe-advancedworkflow/pull/494
- https://github.com/silverstripe/silverstripe-behat-extension/pull/247
- https://github.com/silverstripe/gha-dispatch-ci/pull/4
- https://github.com/silverstripe/silverstripe-elemental/pull/1074

**Comment by GuySartorelli** [comment]
PRs merged. Reassigning to @emteknetnz to verify that broken builds are now green
