### ISSUE TITLE
Fresh install of sink won't allow user to edit pages because of fluent error

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/recipe-kitchen-sink#63]
On a fresh install of the sink 5.x-dev on PHP8.3, I'm getting this error from Fluent whenever I try to access any page in the CMS.
```
[Emergency] Uncaught TypeError: TractorCow\Fluent\Model\RecordLocale::__construct(): Argument #2 ($locale) must be of type TractorCow\Fluent\Model\Locale, null given, called in /home/max/Projects/test5x/vendor/silverstripe/framework/src/Core/Injector/InjectionCreator.php on line 35
```

I'm not getting the error on the sink 5.2.x-dev. So it must be something that got added recently.

~I'm a bit concern that this wasn't picked up by our CI~. [It got picked up by our CI](https://github.com/silverstripe/recipe-kitchen-sink/actions/runs/9392337106/job/25866387621) so GitHub action FTW. Still it's a bit confusing how we ended up merging something that completely bust the CMS.

## Acceptance criteria
- Fix the bug.
- Do a root cause analysis to understand how this issue got introduced and how it got past peer review.

**Comment by emteknetnz** [comment]
Duplicate https://github.com/silverstripe/.github/issues/271
